### ISSUE TITLE
Progress bar too big

### ISSUE THREAD

**Issue by ShayBox** [jamiepine/cache-monkey#12]
I'm running this on linux if it matters, but the progress bar keeps going way past where it's supposed to
![image](https://user-images.githubusercontent.com/9505196/57998812-07299600-7aa1-11e9-8351-df1edc6936b3.png)

Also is there a way to disable the program specific titlebar to use the system titlebar, program specific titlebars are bad.

**Comment by AlekEagleYT** [comment]
This was my fault, I did something to the way the progress bar functions, and I don't quite know what happened. Also, since this is an electron Vue program, I'm not quite sure if we can do a system loading bar.

**Comment by ShayBox** [comment]
You would have to disable the built in one, I don't know how to do that, and then enable the system one
https://github.com/jamiepine/cache-monkey/blob/master/src/main/index.js#L28
Probably with a toggle box in the settings
