### ISSUE TITLE
Discord PTB option

### ISSUE THREAD

**Issue by kot83** [jamiepine/cache-monkey#9]
- Discord PTB does not get detected.

**Comment by TheTetrabyte** [comment]
Discord ptb works fine, there just is not a button for it in the UI, we will add this next update. In the mean time you can add it manually by clicking

`"Choose Cache Directory"` 

Then on windows set it to `%appdata%/discordptb/Cache`

**Comment by TheTetrabyte** [comment]
Here is a screenshot of the settings page and the app page once I scanned after adding cache.

![CacheMonkey Settings](https://notify-me.is-a-good.site/nZoA79Kc.png)

![CacheMonkey Main Page](https://notify-me.is-a-good.site/oScvn6CX.png)
